proxy:
  http: socks5://127.0.0.1:7890
  https: socks5://127.0.0.1:7890
max_threads: 1
headed: 0
header:
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/118.0.0.0 Safari/537.36
inject_js: "script.js"
save: "output"
user: gogeweb3